<?php

namespace App\Repository;

use App\Models\Entities\Korisnik;
use App\Models\Entities\Uloge;
use App\Models\Entities\Klijent;
use App\Models\Entities\Lekar;

use Doctrine\DBAL\Exception\UniqueConstraintViolationException;

/**
 * KlijentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KlijentRepository extends \Doctrine\ORM\EntityRepository
{
    public function kreirajKlijenta($postData){
        $korisnik = new Korisnik;
        $korisnik->setSifra(password_hash($postData["sifra"], PASSWORD_DEFAULT));
        $korisnik->setIme($postData["ime"]);
        $korisnik->setPrezime($postData["prezime"]);
        $korisnik->setJmbg($postData["jmbg"]);
        $korisnik->setBrlk($postData["lk"]);
        $korisnik->setPol($postData["pol"]);
        $korisnik->setBrtel($postData["tel"]);
        $korisnik->setEmail($postData["email"]);
        $klijentRepo = service("doctrine")->em->getRepository(Uloge::class);
        $uloga = $klijentRepo->findOneby(['nazivuloge'=>'Klijent']);
        $korisnik->setIduloge($uloga);

        $lekarRepo = service("doctrine")->em->getRepository(Lekar::class);
        $izabraniLekar = $lekarRepo->findOneby(['idlekar'=> (int)$postData["lekar"]]);

        if(!$izabraniLekar){
          return ["success"=>false,"errors"=>['lekar'=>"Izabrani lekar ne postoji."]];
        }

        $klijent = new Klijent;
        $klijent->setIdklijent($korisnik);
        $klijent->setIzabraniLekar($izabraniLekar);


        $this->_em->persist($klijent);
        try {
          $this->_em->flush();
        }
        catch (UniqueConstraintViolationException $e) {
           return ["success"=>false,"errors"=>['email'=>"Email je vec u upotrebi."]];
        }
        return ["success"=>true,"errors"=>[],'klijent'=>$klijent];
        
   
     
        
    }
}
