<?php

namespace App\Repository;

/**
 * KorisnikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KorisnikRepository extends \Doctrine\ORM\EntityRepository
{
}
