<?php

namespace App\Repository;

/**
 * LekarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LekarRepository extends \Doctrine\ORM\EntityRepository
{
    public function dohvatiLekareOpstePrakse(){

        $doctors =  $this->findBy(['nazivstruke'=> "Opsta medicina"]);
        $array = array();
        foreach ($doctors as $doctor) {
            $temp = $doctor->getIdlekar();
            $doctorObject = (object)[
                "id" =>  $temp->getIdk(),
                "ime" => $temp->getIme()." ".$temp->getPrezime()
            ];
            
            $array[]=$doctorObject;      
        }

        return  $array;
    }

}
