<?php

namespace App\Repository;

/**
 * LekarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LekarRepository extends \Doctrine\ORM\EntityRepository
{
    public function dohvatiLekareOpstePrakse(){
        return $this->findAll();
    }

}
