<?php

namespace App\Repository;

/**
 * LinkoviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkoviRepository extends \Doctrine\ORM\EntityRepository
{
}
