<?php

namespace App\Repository;



/**
 * PitanjeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitanjeRepository extends \Doctrine\ORM\EntityRepository {
    
    public function dohvBrPitanja(){
        
        $brPitanja = $this->createQueryBuilder('a')
            ->select('count(a.idpitanje)')
            ->getQuery()
            ->getSingleScalarResult();
        return $brPitanja;
    }
    
    public function getPitanjeById($id){
       
       return  $this->findOneBy(array('idpitanje' => $id));
       
    }

    public function getAllQuestions($page) {
        if (!$page)
        $page=1;
        return $this->findBy(
                        array(),
                        array('datumvreme' => 'DESC'),
                        2,
                        ($page-1)*2
        );
    }
    
    public function dodajOdgovor($postData, $data){ //,$userId;
        
        $pitanje = $this->getPitanjeById($data["idpitanje"]);
        $pitanje->setOdgovor($postData["message"]);
        $pitanje->setIdlekar($data["lekar"]);
             
        
  

        $this->_em->persist($pitanje);
        
        try {
          $this->_em->flush();
         
         
        }
        catch (Exception $e) {
           return ["success"=>false,"errors"=>['email'=>"Doslo je do greske prilikom pokusaja ubacivanja pitanja u bazu"]];
        }
        return ["success"=>true,"errors"=>[]];
             
    }

}
