<?php

namespace App\Repository;



/**
 * PitanjeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitanjeRepository extends \Doctrine\ORM\EntityRepository {
    
    public function dohvBrPitanja(){
        
        $brPitanja = $this->createQueryBuilder('a')
            ->select('count(a.idpitanje)')
            ->getQuery()
            ->getSingleScalarResult();
        return $brPitanja;
    }

    public function getAllQuestions($page) {
        if (!$page)
        $page=1;
        return $this->findBy(
                        array(),
                        array('datumvreme' => 'DESC'),
                        2,
                        ($page-1)*2
        );
    }

}
