<?php

namespace App\Repository;

use App\Models\Entities\Pitanje;
use App\Models\Entities\Pitanjeklijent;
use App\Models\Entities\Struka;
use App\Models\Entities\Klijent;

/**
 * PitanjeklijentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitanjeklijentRepository extends \Doctrine\ORM\EntityRepository
{
    public function kreirajPitanjeklijent($postData, $id){ //,$userId;
        $pitanje = new Pitanje;
        $pitanje->setNaslov($postData["subject"]);
        $pitanje->setTekstpitanja($postData["message"]);
       
        $strukarep = service('doctrine')->em->getRepository(Struka::class);
        $struka=$strukarep->findOneBy(['nazivstruke'=>$postData["struka"]]);
        $pitanje->setNazivstruke($struka);
        $pitanje->setGostpitao(false);  
        
        $pitanjeKlijent= new Pitanjeklijent;
        $pitanjeKlijent->setIdpitanje($pitanje);
        
        $klijentrep = service('doctrine')->em->getRepository(Klijent::class);
        $klijent=$klijentrep->findOneBy(['idklijent'=>$id]);
        $pitanjeKlijent->setIdklijent($klijent);   //$userId;

        
        
        

        $this->_em->persist($pitanjeKlijent);
        
        try {
          $this->_em->flush();
         
         
        }
        catch (Exception $e) {
           return ["success"=>false,"errors"=>['email'=>"Doslo je do greske prilikom pokusaja ubacivanja pitanja u bazu"]];
        }
        return ["success"=>true,"errors"=>[]];
             
    }
    
    
    
}
