<?php

namespace App\Repository;

use App\Models\Entities\Pitanje;
use App\Models\Entities\Pitanjeklijent;

/**
 * PitanjeklijentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitanjeklijentRepository extends \Doctrine\ORM\EntityRepository
{
    public function kreirajPitanjeklijent($postData, $userId){
        $pitanje = new Pitanje;
        $pitanje->setNaslov($postdata["subject"]);
        $pitanje->setTekstpitanja($postdata["message"]);
        $pitanje->setNazivstruke($postdata["struka"]);
        
        $pitanjeKlijent= new Pitanjeklijent;
        $pitanjeKlijent->setIdpitanje($pitanje->getIdpitanje());
        $pitanjeKlijent->setIdklijent($userId);
        
        

        $this->_em->persist($pitanjeKlijent);
        try {
          $this->_em->flush();
        }
        catch (Exception $e) {
           return ["success"=>false,"errors"=>['email'=>"Doslo je do greske prilikom pokusaja ubacivanja pitanja u bazu"]];
        }
        return ["success"=>true,"errors"=>[]];
             
    }
    
    
    
}
