<?php

namespace App\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PitanjeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitanjeRepository extends \Doctrine\ORM\EntityRepository {

    public function getAllQuestions($page) {
        if (!$page)
        $page=1;
        return $this->findBy(
                        array(),
                        array('datumvreme' => 'DESC'),
                        2,
                        ($page-1)*2
        );
    }

}
