<?php

namespace App\Repository;

use App\Models\Entities\Korisnik;
use App\Models\Entities\Uloge;
use App\Models\Entities\Sluzbenik;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;


/**
 * SluzbenikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SluzbenikRepository extends \Doctrine\ORM\EntityRepository
{
    public function kreirajSluzbenika($postData){
        $korisnik = new Korisnik;
        $korisnik->setSifra(password_hash($postData["sifra"], PASSWORD_DEFAULT));
        $korisnik->setIme($postData["ime"]);
        $korisnik->setPrezime($postData["prezime"]);
        $korisnik->setJmbg($postData["jmbg"]);
        $korisnik->setBrlk($postData["lk"]);
        $korisnik->setPol($postData["pol"]);
        $korisnik->setBrtel($postData["tel"]);
        $korisnik->setEmail($postData["email"]);
        $klijentRepo = service("doctrine")->em->getRepository(Uloge::class);
        $uloga = $klijentRepo->findOneby(['nazivuloge'=>'Sluzbenik']);
        $korisnik->setIduloge($uloga);


    
        $this->_em->persist($korisnik);
        try {
          $this->_em->flush();
        }
        catch (UniqueConstraintViolationException $e) {
           return ["success"=>false,"errors"=>['email'=>"Email je vec u upotrebi."]];
        }
        return ["success"=>true,"errors"=>[],'klijent'=>$korisnik];
        
   
     
        
    }
}
