<?php

namespace App\Repository;

use App\Models\Entities\Stavkakartona;

/**
 * StavkakartonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StavkakartonaRepository extends \Doctrine\ORM\EntityRepository
{
    public function countStavkeById($id){
        $qb = $this->_em->createQueryBuilder();
        $qb
        ->from(Stavkakartona::class,"s")
        ->select('count(s.idstavka)')
        ->where('s.idklijent = :param1')
        ->setParameter('param1', $id);

       return $qb->getQuery()->getSingleScalarResult();
    }
}
