<?php

namespace App\Repository;

/**
 * StavkakartonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StavkakartonaRepository extends \Doctrine\ORM\EntityRepository
{
}
