<?php

namespace App\Repository;

use App\Models\Entities\Stavkakartona;
use App\Models\Entities\Klijent;
use App\Models\Entities\Lekar;
use App\Models\Entities\Usluga;
/**
 * StavkakartonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StavkakartonaRepository extends \Doctrine\ORM\EntityRepository
{
    public function countStavkeById($id){
        $qb = $this->_em->createQueryBuilder();
        $qb
        ->from(Stavkakartona::class,"s")
        ->select('count(s.idstavka)')
        ->where('s.idklijent = :param1')
        ->setParameter('param1', $id);

       return $qb->getQuery()->getSingleScalarResult();
    }
    public function dodajStavku($postData, $idLekar){
        $id = intval($postData["id"]);
        $stavka = new Stavkakartona;

        $klijentRepo = service("doctrine")->em->getRepository(Klijent::class);
        $lekarRepo = service("doctrine")->em->getRepository(Lekar::class);
        $uslugaRepo = service("doctrine")->em->getRepository(Usluga ::class);

        $stavka->setIdKlijent($klijentRepo->findOneBy(["idklijent"=>$id]));
        $stavka->setPregledobavio($lekarRepo->findOneBy(["idlekar"=>$idLekar]));
        $usluga = $uslugaRepo->findOneBy(["imeusluge"=>$postData["usluga"]]);

        $stavka->setImeusluge($usluga);
        $stavka->setNazivstruke($usluga->getNazivstruke());
        $stavka->setDijagnostika($postData["dijagnoza"]);
        $stavka->setPreporucenaterapija($postData["terapija"]);
        $stavka->setInternanapomena($postData["napomena"]);
        
        $this->_em->persist($stavka);
        $this->_em->flush();


    }
}
