<?php

namespace App\Repository;

/**
 * StrukaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrukaRepository extends \Doctrine\ORM\EntityRepository
{
     public function dohvatiStruke(){

        $arr = $this->findAll();
        $arr1= array();
        foreach ($arr as $a){
            $arr1[]= $a->getNazivStruke();
          
        }
        return $arr1;
    }
    
}
