<?php

namespace App\Repository;

/**
 * UlogeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UlogeRepository extends \Doctrine\ORM\EntityRepository
{
   
}
