<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pregled extends \App\Models\Entities\Pregled implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idpregled', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idlekar', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'jeonline', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idklijent', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idtermin'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idpregled', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idlekar', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'jeonline', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idklijent', '' . "\0" . 'App\\Models\\Entities\\Pregled' . "\0" . 'idtermin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pregled $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdpregled($idpregled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpregled', [$idpregled]);

        return parent::setIdpregled($idpregled);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpregled()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpregled();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpregled', []);

        return parent::getIdpregled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdlekar($idlekar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdlekar', [$idlekar]);

        return parent::setIdlekar($idlekar);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdlekar()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdlekar();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlekar', []);

        return parent::getIdlekar();
    }

    /**
     * {@inheritDoc}
     */
    public function setJeonline($jeonline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJeonline', [$jeonline]);

        return parent::setJeonline($jeonline);
    }

    /**
     * {@inheritDoc}
     */
    public function getJeonline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJeonline', []);

        return parent::getJeonline();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdklijent($idklijent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdklijent', [$idklijent]);

        return parent::setIdklijent($idklijent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdklijent()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdklijent();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdklijent', []);

        return parent::getIdklijent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtermin($idtermin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtermin', [$idtermin]);

        return parent::setIdtermin($idtermin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtermin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtermin', []);

        return parent::getIdtermin();
    }

}
