<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Stavkakartona extends \App\Models\Entities\Stavkakartona implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'idstavka', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'dijagnostika', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'preporucenaterapija', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'internanapomena', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'idklijent', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'pregledobavio', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'imeusluge', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'idfajl'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'idstavka', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'dijagnostika', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'preporucenaterapija', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'internanapomena', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'idklijent', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'pregledobavio', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'imeusluge', '' . "\0" . 'App\\Models\\Entities\\Stavkakartona' . "\0" . 'idfajl'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Stavkakartona $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdstavka()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdstavka();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdstavka', []);

        return parent::getIdstavka();
    }

    /**
     * {@inheritDoc}
     */
    public function setDijagnostika($dijagnostika)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDijagnostika', [$dijagnostika]);

        return parent::setDijagnostika($dijagnostika);
    }

    /**
     * {@inheritDoc}
     */
    public function getDijagnostika()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDijagnostika', []);

        return parent::getDijagnostika();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreporucenaterapija($preporucenaterapija)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreporucenaterapija', [$preporucenaterapija]);

        return parent::setPreporucenaterapija($preporucenaterapija);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreporucenaterapija()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreporucenaterapija', []);

        return parent::getPreporucenaterapija();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternanapomena($internanapomena = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternanapomena', [$internanapomena]);

        return parent::setInternanapomena($internanapomena);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternanapomena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternanapomena', []);

        return parent::getInternanapomena();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdklijent(\App\Models\Entities\Klijent $idklijent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdklijent', [$idklijent]);

        return parent::setIdklijent($idklijent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdklijent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdklijent', []);

        return parent::getIdklijent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPregledobavio(\App\Models\Entities\Lekar $pregledobavio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPregledobavio', [$pregledobavio]);

        return parent::setPregledobavio($pregledobavio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPregledobavio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPregledobavio', []);

        return parent::getPregledobavio();
    }

    /**
     * {@inheritDoc}
     */
    public function setImeusluge(\App\Models\Entities\Usluga $imeusluge = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImeusluge', [$imeusluge]);

        return parent::setImeusluge($imeusluge);
    }

    /**
     * {@inheritDoc}
     */
    public function getImeusluge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImeusluge', []);

        return parent::getImeusluge();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdfajl(\App\Models\Entities\Fajl $idfajl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdfajl', [$idfajl]);

        return parent::addIdfajl($idfajl);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdfajl(\App\Models\Entities\Fajl $idfajl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdfajl', [$idfajl]);

        return parent::removeIdfajl($idfajl);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfajl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfajl', []);

        return parent::getIdfajl();
    }

}
